# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            1saeed.dev
tagline:          'story of a developer :)'
description:      'stories from a developer'
url:              https://1saeed.dev
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Saeed Salehi'
  url:            https://twitter.com/1saeedsalehi

paginate:         5



plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
# Custom vars
version:            0.9
sidebar_home_link:  true
page:
  comments: true
disqus:
shortname : '1saeedsalehi'
github:
  repo:             https://github.com/1saeedsalehi
