# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            یک سعید صالحی
tagline:          'داستان یک برنامه نویس گیک'
description:      'داستان یک برنامه نویس گیک طور'
url:              http://1saeedsalehi.ir
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'سعید صالحی'
  url:            https://twitter.com/1saeedsalehi

paginate:         5



plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            0.9
sidebar_home_link:  true
page:
  comments: true
disqus:
shortname : '1saeedsalehi'
github:
  repo:             https://github.com/1saeedsalehi
